type SnapshotField = { fieldName: string; value: string | null; normalizedValue: string | null; confidence: number | null; source: string; validationStatus: string; validationNotes?: string | null; boundingBox?: unknown };
type SnapshotExtraction = { status?: string; extractionVersion?: string; confidence?: number | null; extractedJson?: unknown; rawText?: string | null; fieldExtractions?: SnapshotField[] } | null;
type SnapshotBarcode = { rawValue: string; symbology: string; confidence: number; decodedDataJson?: unknown; decodedAt: string };
type SnapshotDocument = { id: string; type: string; name: string; fileName: string; status: string; extraction?: SnapshotExtraction; barcodes?: SnapshotBarcode[] };
type Snapshot = { generatedAt?: string; applicationId?: string; documents?: SnapshotDocument[] } | null | undefined;

export default function ExtractionReview({ snapshot }: { snapshot: Snapshot }) {
  const documents = Array.isArray(snapshot?.documents) ? snapshot.documents : [];
  if (!snapshot || documents.length === 0) return <section className="card"><h2 className="text-lg font-semibold text-slate-900">Extracted data by document</h2><p className="mt-2 text-sm text-slate-600">No generated PDF snapshot is available yet. Click <strong>Generate populated PDF</strong> first; this panel will then show the data used for that PDF.</p></section>;
  const generatedAt = snapshot.generatedAt ? new Date(snapshot.generatedAt).toLocaleString() : 'unknown time';
  return <section><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Extracted data used for latest generated PDF</h2><p className="mt-1 text-sm text-slate-600">Snapshot generated {generatedAt}. This panel is not reading later live extraction changes.</p></div><span className="badge bg-slate-100 text-slate-800">PDF generation snapshot</span></div><div className="mt-4 space-y-6">{documents.map((document) => { const extraction = document.extraction ?? null; const fields = Array.isArray(extraction?.fieldExtractions) ? extraction.fieldExtractions : []; const barcodes = Array.isArray(document.barcodes) ? document.barcodes : []; const json = { document: { id: document.id, type: document.type, name: document.name, fileName: document.fileName, status: document.status }, extraction: extraction ? { status: extraction.status, version: extraction.extractionVersion, confidence: extraction.confidence, extractedJson: extraction.extractedJson, rawText: extraction.rawText, fields } : null, barcodes }; return <article key={document.id} className="card overflow-hidden"><div className="flex items-start justify-between gap-4 border-b border-slate-200 pb-4"><div><h3 className="font-semibold text-slate-900">{document.name}</h3><p className="mt-1 text-sm text-slate-500">{document.type} · {document.fileName}</p></div><span className="badge bg-slate-100 text-slate-700">{document.status}</span></div><div className="mt-4 grid gap-5 lg:grid-cols-2"><div><h4 className="text-sm font-semibold text-slate-800">Fields used for PDF</h4>{fields.length ? <div className="mt-2 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-slate-600"><tr><th className="px-2 py-2">Field</th><th className="px-2 py-2">Value</th><th className="px-2 py-2">Confidence</th><th className="px-2 py-2">Source</th><th className="px-2 py-2">Validation</th></tr></thead><tbody>{fields.map((field, index) => <tr key={`${field.fieldName}-${index}`} className="border-t border-slate-100"><td className="px-2 py-2 font-mono">{field.fieldName}</td><td className="px-2 py-2">{field.value ?? '—'}</td><td className="px-2 py-2">{field.confidence == null ? '—' : `${Math.round(field.confidence * 100)}%`}</td><td className="px-2 py-2">{field.source}</td><td className="px-2 py-2">{field.validationStatus}</td></tr>)}</tbody></table></div> : <p className="mt-2 text-sm text-slate-700">No extraction fields were available for this document.</p>}</div><div><h4 className="text-sm font-semibold text-slate-800">PDF-generation JSON</h4><details open className="mt-2"><summary className="cursor-pointer text-sm text-slate-600">View snapshot JSON</summary><pre className="mt-2 max-h-[32rem] overflow-auto rounded-md bg-slate-950 p-3 text-xs leading-5 text-slate-100">{JSON.stringify(json, null, 2)}</pre></details></div></div></article>; })}</div></section>;
}