import Link from 'next/link';
import { notFound } from 'next/navigation';
import { prisma } from '@/lib/db';
import { requirePageRole } from '@/lib/auth/session';
import ExtractionReview from './ExtractionReview';

export const dynamic = 'force-dynamic';

export default async function AdminApplicationDetailPage({ params }: { params: { id: string } }) {
  await requirePageRole(['ADMIN', 'SUPER_ADMIN'], `/admin/applications/${params.id}`);
  const application = await prisma.application.findUnique({ where: { id: params.id }, include: { user: { select: { firstName: true, surname: true, email: true, mobileNumber: true } }, product: { select: { name: true } }, documents: { where: { status: { not: 'REPLACED' } }, include: { documentType: { select: { name: true, code: true } }, extractions: { orderBy: { createdAt: 'desc' }, include: { fieldExtractions: { orderBy: { createdAt: 'asc' } } } }, barcodes: { orderBy: { decodedAt: 'desc' } } }, orderBy: { createdAt: 'desc' } }, priceCalculations: { orderBy: { createdAt: 'desc' }, take: 5 }, statusHistory: { orderBy: { createdAt: 'desc' } }, generatedDocuments: { orderBy: { createdAt: 'desc' } } } });
  if (!application) notFound();
  return <main className="mx-auto max-w-7xl px-4 py-10"><Link href="/admin/applications" className="text-sm font-medium text-slate-700 hover:underline">â† Applications</Link><header className="mt-4 border-b border-slate-200 pb-6"><p className="text-sm text-slate-500">{application.applicationNumber}</p><h1 className="mt-1 text-3xl font-bold text-slate-900">{application.product.name}</h1><p className="mt-2 text-slate-600">{application.user.firstName} {application.user.surname} Â· {application.user.email} Â· {application.user.mobileNumber}</p></header><section className="mt-8 grid gap-4 sm:grid-cols-3"><div className="card"><p className="text-sm text-slate-500">Status</p><p className="mt-2 font-semibold text-slate-900">{application.status.replaceAll('_', ' ')}</p></div><div className="card"><p className="text-sm text-slate-500">Payment</p><p className="mt-2 font-semibold text-slate-900">{application.paymentStatus}</p></div><div className="card"><p className="text-sm text-slate-500">Price</p><p className="mt-2 font-semibold text-slate-900">{application.price === null ? 'Not calculated' : `${application.currency} ${application.price.toFixed(2)}`}</p></div></section><section className="mt-8">{application.generatedDocuments.length > 0 ? <div className="mt-4 space-y-2">{application.generatedDocuments.map((document) => <a key={document.id} href={`/api/admin/applications/${application.id}/pdf/${document.id}`} target="_blank" rel="noreferrer" className="block rounded-md border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 hover:bg-slate-50">Open populated PDF: {document.fileName}</a>)}</div> : null}</section><section className="mt-10"><ExtractionReview documents={application.documents} /></section><section className="mt-10"><h2 className="text-lg font-semibold text-slate-900">Documents</h2><div className="mt-4 space-y-3">{application.documents.map((document) => <div key={document.id} className="card flex items-center justify-between gap-4"><div><p className="font-semibold text-slate-900">{document.documentType.name}</p><p className="mt-1 text-sm text-slate-500">{document.originalFileName} Â· {document.status}</p></div><span className="badge bg-slate-100 text-slate-700">{document.mimeType}</span></div>)}</div></section><section className="mt-10"><h2 className="text-lg font-semibold text-slate-900">Status history</h2><div className="mt-4 space-y-3">{application.statusHistory.map((entry) => <div key={entry.id} className="card text-sm"><span className="font-medium text-slate-900">{entry.newStatus.replaceAll('_', ' ')}</span><span className="ml-2 text-slate-500">{new Date(entry.createdAt).toLocaleString()}</span>{entry.reason ? <p className="mt-1 text-slate-600">{entry.reason}</p> : null}</div>)}</div></section></main>;
}