import { prisma } from '@/lib/db';
import { EXTRACTION_VERSION } from '@/lib/extraction/types';
import { computeInitials, normalizeWhitespace } from '@/lib/extraction/normalizers';
import { validateSouthAfricanId } from '@/lib/validation/sa-id';
import { DOCUMENT_TYPE_CODES } from '@/lib/extraction';

export interface ResolvedValueSource { sourcePath: string; value: string | null; confidence: number | null; validationStatus: string; source: string; requiresReview: boolean; origin: 'MANUAL_CORRECTION' | 'EXTRACTION' | 'CUSTOMER_PROFILE' | 'CALCULATED' | 'NONE'; documentId?: string | null; }
export interface ResolvedOwnerData { identificationType: 'RSA_ID' | 'FOREIGN_ID' | 'TRAFFIC_REGISTER' | 'BUSINESS_REGISTRATION' | null; trafficRegisterNumber: string | null; idNumber: string | null; foreignIdNumber: string | null; businessRegistrationNumber: string | null; countryOfIssue: string | null; surname: string | null; firstNames: string | null; initials: string | null; email: string | null; homeTelephone: string | null; dayTimeTelephone: string | null; fax: string | null; cellphone: string | null; postalAddress: string | null; streetAddress: string | null; suburb: string | null; city: string | null; postalCode: string | null; }
export interface ResolvedVehicleData { registrationNumber: string | null; licenceNumber: string | null; vehicleRegisterNumber: string | null; vin: string | null; chassisNumber: string | null; engineNumber: string | null; make: string | null; model: string | null; seriesName: string | null; vehicleType: string | null; tareWeight: string | null; gvm: string | null; odometer: string | null; noOdometer: boolean | null; steeringWheelPosition: 'DRAWN' | 'LEFT' | 'CENTRE' | 'RIGHT' | null; }
export interface ResolvedApplicationData { application: { id: string; applicationNumber: string; status: string; paymentStatus: string; ownerType: 'INDIVIDUAL' | 'ORGANISATION'; vehicleClass: string; productId: string; productSlug: string; productName: string; currentExpiryDate: string | null; applicationDate: string; completedAt: string | null; }; owner: ResolvedOwnerData; vehicle: ResolvedVehicleData; organisationProxy: Record<string, string | null>; organisationRepresentative: Record<string, string | null>; officeUse: Record<string, string | null>; declaration: { date: string | null; signatureProvided: boolean }; sources: Record<string, ResolvedValueSource>; needsReview: string[]; extractionVersion: string; }

function better(a: ResolvedValueSource, b: ResolvedValueSource) { if (a.requiresReview !== b.requiresReview) return !a.requiresReview; return (a.confidence ?? 0) > (b.confidence ?? 0); }
function steering(value: string | null): ResolvedVehicleData['steeringWheelPosition'] { switch (value?.toUpperCase()) { case 'DRAWN': return 'DRAWN'; case 'LEFT': return 'LEFT'; case 'CENTRE': case 'CENTER': return 'CENTRE'; case 'RIGHT': return 'RIGHT'; default: return null; } }

export async function resolveApplicationData(applicationId: string): Promise<ResolvedApplicationData> {
  const app = await prisma.application.findUniqueOrThrow({ where: { id: applicationId }, include: { product: true, user: true, documents: { where: { status: { not: 'REPLACED' } }, include: { documentType: true, extractions: { orderBy: { createdAt: 'desc' }, take: 1, include: { fieldExtractions: true } } }, orderBy: { createdAt: 'desc' } }, manualCorrections: { orderBy: { createdAt: 'asc' } }, organisationProxy: true, organisationRepresentative: true } });
  const sources: Record<string, ResolvedValueSource> = {};
  const byType = new Map<string, typeof app.documents[number]>(); for (const d of app.documents) if (!byType.has(d.documentType.code)) byType.set(d.documentType.code, d);
  const extracted = new Map<string, Record<string, ResolvedValueSource>>();
  for (const [code, d] of byType) { const map: Record<string, ResolvedValueSource> = {}; for (const f of d.extractions[0]?.fieldExtractions ?? []) { const v: ResolvedValueSource = { sourcePath: `${code}.${f.fieldName}`, value: f.normalizedValue ?? f.value ?? null, confidence: f.confidence, validationStatus: f.validationStatus, source: f.source, requiresReview: f.validationStatus === 'NEEDS_REVIEW' || f.validationStatus === 'INVALID', origin: 'EXTRACTION', documentId: d.id }; if (!map[f.fieldName] || better(v, map[f.fieldName]!)) map[f.fieldName] = v; } extracted.set(code, map); }
  const corrections = new Map<string, ResolvedValueSource>(); for (const c of app.manualCorrections) if (c.newValue != null) corrections.set(c.fieldName, { sourcePath: c.fieldName, value: c.newValue, confidence: 1, validationStatus: 'VALID', source: 'MANUAL', requiresReview: false, origin: 'MANUAL_CORRECTION' });
  const resolve = (path: string, fallback?: ResolvedValueSource): ResolvedValueSource => { const v = corrections.get(path) ?? fallback ?? { sourcePath: path, value: null, confidence: null, validationStatus: 'NEEDS_REVIEW', source: 'SYSTEM', requiresReview: false, origin: 'NONE' }; v.sourcePath = path; sources[path] = v; return v; };
  const from = (code: string, field: string) => extracted.get(code)?.[field] ?? { sourcePath: `${code}.${field}`, value: null, confidence: null, validationStatus: 'NEEDS_REVIEW', source: 'SYSTEM', requiresReview: false, origin: 'NONE' as const };
  const usable = (v: ResolvedValueSource) => v.value != null && v.validationStatus === 'VALID' && !v.requiresReview ? normalizeWhitespace(v.value) : null;
  const customer = (path: string, value: string | null) => resolve(path, { sourcePath: path, value, confidence: 1, validationStatus: value ? 'VALID' : 'NEEDS_REVIEW', source: 'CUSTOMER_PROFILE', requiresReview: false, origin: value ? 'CUSTOMER_PROFILE' : 'NONE' });
  const ID = DOCUMENT_TYPE_CODES.SOUTH_AFRICAN_ID, POR = DOCUMENT_TYPE_CODES.PROOF_OF_RESIDENCE, DISC = DOCUMENT_TYPE_CODES.VEHICLE_LICENCE_DISC;
  const idValue = resolve('ID.idNumber', from(ID, 'idNumber')); const idCheck = idValue.value ? validateSouthAfricanId(idValue.value) : null; const surname = resolve('ID.surname', from(ID, 'surname')); const firstNames = resolve('ID.firstNames', from(ID, 'firstNames')); const initialsDoc = resolve('ID.initials', from(ID, 'initials')); const initials = resolve('OWNER.initials', { sourcePath: 'OWNER.initials', value: usable(initialsDoc) ?? (usable(firstNames) ? computeInitials(usable(firstNames)!) : null), confidence: .9, validationStatus: 'VALID', source: 'CALCULATED', requiresReview: false, origin: 'CALCULATED' });
  const email = customer('CUSTOMER.email', app.user.email), cellphone = customer('CUSTOMER.mobileNumber', app.user.mobileNumber);
  const addressLine1 = resolve('POR.addressLine1', from(POR, 'addressLine1')); const addressLine2 = resolve('POR.addressLine2', from(POR, 'addressLine2')); const suburb = resolve('POR.suburb', from(POR, 'suburb')); const city = resolve('POR.city', from(POR, 'city')); const postalCode = resolve('POR.postalCode', from(POR, 'postalCode')); const province = resolve('POR.province', from(POR, 'province'));
  const reg = resolve('LICENCE_DISC.registrationNumber', from(DISC, 'registrationNumber')); const licence = resolve('LICENCE_DISC.licenceNumber', from(DISC, 'licenceNumber')); const vehicleReg = resolve('LICENCE_DISC.vehicleRegisterNumber', from(DISC, 'vehicleRegisterNumber')); const vin = resolve('LICENCE_DISC.vin', from(DISC, 'vin')); const chassis = resolve('LICENCE_DISC.chassisNumber', from(DISC, 'chassisNumber')); const engine = resolve('LICENCE_DISC.engineNumber', from(DISC, 'engineNumber')); const make = resolve('LICENCE_DISC.make', from(DISC, 'make')); const model = resolve('LICENCE_DISC.model', from(DISC, 'model')); const series = resolve('LICENCE_DISC.seriesName', from(DISC, 'seriesName')); const vehicleType = resolve('LICENCE_DISC.vehicleType', from(DISC, 'vehicleType')); const tare = resolve('LICENCE_DISC.tareWeight', from(DISC, 'tareWeight')); const gvm = resolve('LICENCE_DISC.gvm', from(DISC, 'gvm')); const odometer = resolve('LICENCE_DISC.odometer', from(DISC, 'odometer')); const expiry = resolve('LICENCE_DISC.expiryDate', from(DISC, 'expiryDate'));
  const officeUse = {} as Record<string, string | null>; for (const k of ['dateOfApplication','counterOfficialName','counterOfficialSignature','dataCapturingOfficialName','dataCapturingOfficialSignature','dataCapturingDate','licenceSerialNumber']) officeUse[k] = usable(resolve(`OFFICE_USE.${k}`));
  const org = (row: Record<string, unknown> | null, prefix: string) => Object.fromEntries(['identificationType','trafficRegisterNumber','identificationNumber','countryOfIssue','surnameAndInitials'].map((k) => [k, typeof row?.[k] === 'string' ? row[k] as string : null]));
  const proxy = org(app.organisationProxy as Record<string, unknown> | null, 'ORG_PROXY'); const rep = org(app.organisationRepresentative as Record<string, unknown> | null, 'ORG_REP');
  const needsReview = Object.entries(sources).filter(([, v]) => v.value == null || v.requiresReview).map(([k]) => k).sort();
  return { application: { id: app.id, applicationNumber: app.applicationNumber, status: app.status, paymentStatus: app.paymentStatus, ownerType: app.ownerType, vehicleClass: app.vehicleClass, productId: app.productId, productSlug: app.product.slug, productName: app.product.name, currentExpiryDate: app.currentExpiryDate?.toISOString().slice(0,10) ?? usable(expiry), applicationDate: app.createdAt.toISOString().slice(0,10), completedAt: app.completedAt?.toISOString().slice(0,10) ?? null }, owner: { identificationType: idCheck?.valid ? 'RSA_ID' : null, trafficRegisterNumber: usable(resolve('ID.trafficRegisterNumber', from(ID, 'trafficRegisterNumber'))), idNumber: usable(idValue), foreignIdNumber: null, businessRegistrationNumber: null, countryOfIssue: usable(resolve('ID.countryOfIssue', from(ID, 'countryOfIssue'))), surname: usable(surname), firstNames: usable(firstNames), initials: usable(initials), email: usable(email), homeTelephone: null, dayTimeTelephone: null, fax: null, cellphone: usable(cellphone), postalAddress: usable(addressLine1), streetAddress: usable(addressLine1), suburb: usable(suburb), city: usable(city), postalCode: usable(postalCode) }, vehicle: { registrationNumber: usable(reg), licenceNumber: usable(licence) ?? usable(reg), vehicleRegisterNumber: usable(vehicleReg), vin: usable(vin), chassisNumber: usable(chassis) ?? usable(vin), engineNumber: usable(engine), make: usable(make), model: usable(model), seriesName: usable(series) ?? usable(model), vehicleType: usable(vehicleType), tareWeight: usable(tare), gvm: usable(gvm), odometer: usable(odometer), noOdometer: null, steeringWheelPosition: null }, organisationProxy: proxy, organisationRepresentative: rep, officeUse, declaration: { date: null, signatureProvided: false }, sources, needsReview, extractionVersion: EXTRACTION_VERSION };
}