import Link from 'next/link';
import { requirePageAuth } from '@/lib/auth/session';
import { listApplicationsForUser } from '@/server/services/application-service';
import DashboardLogoutButton from './DashboardLogoutButton';

export const dynamic = 'force-dynamic';
const statusLabels: Record<string, string> = { DRAFT: 'Draft', DOCUMENTS_REQUIRED: 'Documents required', DOCUMENTS_UPLOADED: 'Documents uploaded', PROCESSING: 'Processing', DOCUMENT_REVIEW: 'Under review', PRICE_CALCULATED: 'Price calculated', AWAITING_PAYMENT: 'Awaiting payment', PAID: 'Paid', IN_PROGRESS: 'In progress', COMPLETED: 'Completed', REJECTED: 'Rejected', CANCELLED: 'Cancelled' };
const paymentLabels: Record<string, string> = { NOT_REQUIRED: 'Not required', PENDING: 'Pending', PAID: 'Paid', FAILED: 'Failed', REFUNDED: 'Refunded' };

export default async function DashboardPage() {
  const session = await requirePageAuth('/dashboard');
  const applications = await listApplicationsForUser(session.sub);
  return <main className="mx-auto max-w-6xl px-4 py-10"><header className="flex flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium uppercase tracking-wide text-slate-700">Customer dashboard</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Your applications</h1><p className="mt-2 text-slate-600">Signed in as {session.email}</p></div><div className="flex flex-wrap items-center gap-2"><Link href="/dashboard/new" className="btn-primary">Start new application</Link><Link href="/" className="btn-secondary">Back to home</Link><DashboardLogoutButton /></div></header><section className="mt-8 grid gap-4 sm:grid-cols-3"><div className="card"><p className="text-sm text-slate-500">Total applications</p><p className="mt-2 text-3xl font-bold text-slate-900">{applications.length}</p></div><div className="card"><p className="text-sm text-slate-500">Needs documents</p><p className="mt-2 text-3xl font-bold text-slate-700">{applications.filter((app) => app.status === 'DOCUMENTS_REQUIRED').length}</p></div><div className="card"><p className="text-sm text-slate-500">Completed</p><p className="mt-2 text-3xl font-bold text-slate-700">{applications.filter((app) => app.status === 'COMPLETED').length}</p></div></section><section className="mt-10"><h2 className="text-lg font-semibold text-slate-900">Application history</h2>{applications.length === 0 ? <div className="card mt-4 text-sm text-slate-600">You have no applications yet. Start a new application to begin.</div> : <div className="mt-4 space-y-4">{applications.map((application) => <Link key={application.id} href={`/dashboard/${application.id}`} className="card block transition-shadow hover:shadow-md"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium text-slate-500">{application.applicationNumber}</p><h3 className="mt-1 text-lg font-semibold text-slate-900">{application.productName}</h3><p className="mt-1 text-sm text-slate-500">Created {new Date(application.createdAt).toLocaleDateString()}</p></div><div className="flex flex-wrap gap-2 text-sm"><span className="badge bg-blue-100 text-slate-800">{statusLabels[application.status] ?? application.status}</span><span className="badge bg-slate-100 text-slate-700">{paymentLabels[application.paymentStatus] ?? application.paymentStatus}</span>{application.price !== null ? <span className="badge bg-slate-100 text-slate-800">{application.currency} {application.price.toFixed(2)}</span> : null}<span className="font-medium text-slate-700">View details â†’</span></div></div></Link>)}</div>}</section></main>;
}